#!/usr/bin/with-contenv sh

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" aima
usermod -o -u "$PUID" aima

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u aima)
User gid:    $(id -g aima)
-------------------------------------
"
chown aima:aima /app
chown aima:aima /config
chown aima:aima /defaults
